version: 2.1

orbs:
  jq: circleci/jq@2.2.0

aliases:
  - &run_integration_repo_job
    run:
      name: Run Taplytics RN SDK Integration Repo
      command: chmod +x .circleci/scripts/trigger-integration-tests.sh && .circleci/scripts/trigger-integration-tests.sh

jobs:
  run-integration-tests:
    docker:
      - image: spotify/alpine
    description: Trigger iOS Integration Tests
    steps:
      - checkout
      - jq/install
      - *run_integration_repo_job

workflows:
  version: 2
  pr-e2e-integration-tests:
    jobs:
      - run-integration-tests
